version: "3.6"

services:
  checkmarx:
    image: checkmarx
    build:
      context: checkmarx
    ports:
      - 5000:5000

  frontengels:
    image: frontengels
    depends_on:
      - checkmarx
    build:
      context: frontengels
    entrypoint:
      - npm
      - start
    ports:
      - 3000:3000
